name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  video_player: ^2.9.5

  # Firebase core dependencies
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  firebase_storage: ^11.6.7
  firebase_messaging: ^14.7.16
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  image_picker: ^1.0.0
  google_maps_flutter: ^2.1.1
  flutter_spinkit: ^5.1.0
  http: 1.4.0
  mime: ^1.0.4
  path: ^1.8.3
  cached_network_image: ^3.3.1
  bottom_drawer: ^0.0.5
  google_fonts: ^4.0.4
  cloud_functions: ^4.6.7
  font_awesome_flutter: ^10.7.0  # Use the latest version
  chewie: ^1.7.1
  shared_preferences: ^2.2.2


 
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome_pizza.jpg
    - assets/pizza1.jpeg
    - assets/Ricotta.jpeg
    - assets/logo1.png
    - assets/logo11.png
    - assets/logo.png
    - assets/Chicken.jpeg
    - assets/chef1.jpg
    - assets/chef2.jpg
    - assets/chef3.jpg
    - assets/your_story.jpg
    - assets/f1.jpeg
    - assets/f2.webp
    - assets/chat_bg.png
    - assets/chat_bot.PNG
    - assets/bg.jpg
    - assets/bgg.webp
    - assets/bgg.jpg
    - assets/user.png
    - assets/chatbot.PNG
    - assets/search.PNG
    - assets/cart.PNG
